CREATE DATABASE  IF NOT EXISTS `hotelsdb` DEFAULT CHARSET=utf8;USE `hotelsdb`;--
-- Table structure for table `HOTEL`
--

DROP TABLE IF EXISTS `HOTEL`;
CREATE TABLE `HOTEL` (
  `ID` varchar(16) NOT NULL,
  `NAME` varchar(250) NOT NULL,
  `POSTAL_CODE` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `RESERVATION`;
CREATE TABLE `RESERVATION` (
  `ID` varchar(16) NOT NULL,
  `HOTEL` varchar(16) NOT NULL,
  `PERSON` varchar(250) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `HOTEL` (`HOTEL`),
  CONSTRAINT `RESERVATION_HOTELID` FOREIGN KEY (`HOTEL`) REFERENCES `HOTEL` (`ID`)
);

--
-- Dumping data for table `HOTEL`
--

LOCK TABLES `HOTEL` WRITE;
INSERT INTO `HOTEL` VALUES
  ('1','Hilton San Francisco Union Square', '94102'),
UNLOCK TABLES;

LOCK TABLES `RESERVATION` WRITE;
INSERT INTO `RESERVATION` VALUES
  ('1','1', 'Luis Mora Medina'),
UNLOCK TABLES;
